import os
os.system("pip install tkinter")
from tkinter import *
try:
	os.system("pip install tkinter")
except Exception as e:
	os.system("pip3 install tkinter")
root = Tk()
Label(text="Create Account",bg="black",fg="white").grid(row=0 ,column=2)
user = Label(text="Username")
username = Entry()
em = Label(text="Email")
email = Entry()
phone = Label(text="Phone Number")
phone_num= Entry()
em.grid(row=2,column=1,pady="10",padx="20")
email.grid(row=2,column=2,pady="10",padx="20")
phone.grid(row=3,column=1,pady="10",padx="20")
phone_num.grid(row=3,column=2,pady="10",padx="20")
passwd = Label(text="Password")
password = Entry()
user.grid(row=5, column=1,pady="10",padx="20")
username.grid(row=5, column=2,pady="10",padx="20")
passwd.grid(row=6, column=1,pady="10",padx="20")
password.grid(row=6, column=2,pady="10",padx="20")
def Save():
	f = open("info.txt","a")
	f.write(f"Username = {username.get()}\n Password = {password.get()}\nEmail = {email.get()}\nPhone number = {phone_num.get()}\n")
submit = Button(text="Submit", command=Save)
submit.grid(row=7, column=2)
root.mainloop()
