import os
os.system("clear")
import time
print("✓"*50)
name = input("Enter Your Name =  ")
time.sleep(1)
print("✓"*50)
time.sleep(1)
print(" "*15,"|  Happy Birthday  |"," "*15)
time.sleep(1)
print("✓"*50)
time.sleep(1)
print(" "*15,"_"*21," "*15)
time.sleep(2)

print("*"*10,"|  "+name+"   |","*"*10)
time.sleep(1)
print("✓"*50)
print("Congratulations for Your Birthday")
time.sleep(1)
print("✓"*50)
time.sleep(2)
os.system("echo hello "+name)
